### PR TITLE
First Pull request

### PR DESCRIPTION
**Pull request by Richiio**

### CODE REVIEW

**Comment by Richiio** [comment]
@GemmaTuron @miquelduranfrigola 

I have been able to upload all the checkpoints by uploading them in bits. The model works perfectly well when the space needed was available. However, it fails once there was no more available space. If the space problem is resolved, this model would be ready for testing or review.

**Comment by Richiio** [comment]
@miquelduranfrigola @GemmaTuron @DhanshreeA 
The corrections suggested during the meeting have been made. This model is now ready for testing

**Comment by GemmaTuron** [comment]
Hi @Richiio 

Please remove the mock.csv file and revise that the gitattributes file tracks only the necessayr files.
Also, update the dockerfile and dependencies to work with higher versions of Python, not 3.7, at least 3.10

**Comment by GemmaTuron** [comment]
Also, in the metadata.json I see there is an empty tag, please change that for "ESKAPE", and the interpretation should be as follows:

    "Interpretation": "Probability of growth inhibition (80% cut off at 50 uM)",
    "Tag": [
        "Cytotoxicity",
        "Antimicrobial activity",
        "ESKAPE"
    ],

**Comment by GemmaTuron** [comment]
@Richiio 

Please, make sure to do ALL edits before pushing a commit, otherwise there are like 5 commits overlapping each other, which is not very good practice.
Make sure that the model test on PR failure is solved in the next commit.

**Comment by Richiio** [comment]
@GemmaTuron @HellenNamulinda 

I've rectified all model dependency issues encountered in the previous commit. 
All edits are accounted for in the latest commit

**Pull request merged**
